# Site settings
title: The Adamant Programming Language Blog
email: site-admin@adamant-lang.org
description: > # this means to ignore newlines until "baseurl:"
  Adamant will be a general-purpose language with high performance,
  deterministic safe resource management, and guaranteed thread safety.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://blog.adamant-lang.org" # the base hostname & protocol for your site
twitter_username: AdamantLang
github_username:  adamant
encoding: UTF-8
permalink: /:year/:title/
paginate: 5
paginate_path: "/page:num"
repository: adamant/blog.adamant-lang.org

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true # disable syntax hilighting server side
incremental: false # jekyll-feed has a bug where it doesn't process tags correctly in incremental
strict_front_matter: true

plugins:
  - jekyll-feed

# Exclude from processing.
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
